### ISSUE TITLE
Directory not found on utils/run_tensorboard.py

### ISSUE THREAD

**Issue by zhengqunkoo** [daniel-kukiela/nmt-chatbot#10]
With `./utils` as working directory, here is traceback, on Ubuntu 16.04.3 LTS.
```
Traceback (most recent call last):
  File "run_tensorboard.py", line 7, in <module>
    p = subprocess.Popen('tensorboard --port 22222 --logdir {}'.format(hparams['out_dir']), stdout=subprocess.PIPE, bufsize=1)
  File "/path/to/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/path/to/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tensorboard --port 22222 --logdir /path/to/nmt-chatbot/model': 'tensorboard --port 22222 --logdir /path/to/nmt-chatbot/model'
```
Appending `shell=True` inside `Popen` seems to fix it though.

**Comment by daniel-kukiela** [comment]
Thank you for a solution.
