### ISSUE TITLE
Train.py Input/output error

### ISSUE THREAD

**Issue by Prickman** [daniel-kukiela/nmt-chatbot#116]
I'm trying to train a chatbot on google colab, and I've trained around 16k steps successfully before encountering this error:

Epoch: 1, steps per epoch: 24349, epoch ends at 24349 steps, learning rate: 0.001 - training

# Job id 0
# Loading hparams from model/hparams
# Updating hparams.num_train_steps: 48698 -> 24349
# Updating hparams.learning_rate: 0.0003 -> 0.001
  saving hparams to model/hparams
  saving hparams to model/best_bleu/hparams
  attention=scaled_luong
  attention_architecture=standard
  avg_ckpts=False
  batch_size=128
  beam_width=20
  best_bleu=0.3703165667940066
  best_bleu_dir=model/best_bleu
  check_special_token=True
  colocate_gradients_with_ops=True
  decay_scheme=
  dev_prefix=data/tst2012.bpe
  dropout=0.2
  embed_prefix=None
  encoder_type=bi
  eos=</s>
  epoch_step=0
  forget_bias=1.0
  infer_batch_size=32
  init_op=uniform
  init_weight=0.1
  learning_rate=0.001
  length_penalty_weight=1.0
  log_device_placement=False
  max_gradient_norm=5.0
  max_train=0
  metrics=['bleu']
  num_buckets=5
  num_decoder_layers=2
  num_decoder_residual_layers=0
  num_embeddings_partitions=0
  num_encoder_layers=2
  num_encoder_residual_layers=0
  num_gpus=1
  num_inter_threads=0
  num_intra_threads=0
  num_keep_ckpts=5
  num_layers=2
  num_train_steps=24349
  num_translations_per_input=20
  num_units=512
  optimizer=adam
  out_dir=model/
  output_attention=True
  override_loaded_hparams=True
  pass_hidden_state=True
  random_seed=None
  residual=False
  sampling_temperature=0.0
  share_vocab=True
  sos=<s>
  src=from
  src_embed_file=
  src_max_len=50
  src_max_len_infer=None
  src_vocab_file=data/vocab.bpe.from
  src_vocab_size=30003
  steps_per_external_eval=None
  steps_per_stats=100
  subword_option=spm
  test_prefix=data/tst2013.bpe
  tgt=to
  tgt_embed_file=
  tgt_max_len=50
  tgt_max_len_infer=None
  tgt_vocab_file=data/vocab.bpe.from
  tgt_vocab_size=30003
  time_major=True
  train_prefix=data/train.bpe
  unit_type=lstm
  vocab_prefix=data/vocab.bpe
  warmup_scheme=t2t
  warmup_steps=0
WARNING:tensorflow:From /content/drive/testingv2/nmt-chatbot/nmt/nmt/utils/iterator_utils.py:190: group_by_window (from tensorflow.contrib.data.python.ops.grouping) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.group_by_window(...)`.
# Use the same embedding for source and target
# creating train graph ...
  num_bi_layers = 1, num_bi_residual_layers=0
  cell 0  LSTM, forget_bias=1WARNING:tensorflow:From /content/drive/testingv2/nmt-chatbot/nmt/nmt/model_helper.py:361: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DropoutWrapper, dropout=0.2   DeviceWrapper, device=/gpu:0
  learning_rate=0.001, warmup_steps=0, warmup_scheme=t2t
  decay_scheme=, start_decay_step=24349, decay_steps 0, decay_factor 1
# Trainable variables
  embeddings/embedding_share:0, (30003, 512), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/fw/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/fw/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/bw/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/bw/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/memory_layer/kernel:0, (1024, 512), 
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (1536, 2048), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/luong_attention/attention_g:0, (), /device:GPU:0
  dynamic_seq2seq/decoder/attention/attention_layer/kernel:0, (1536, 512), /device:GPU:0
  dynamic_seq2seq/decoder/output_projection/kernel:0, (512, 30003), 
# Use the same embedding for source and target
# creating eval graph ...
  num_bi_layers = 1, num_bi_residual_layers=0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
# Trainable variables
  embeddings/embedding_share:0, (30003, 512), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/fw/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/fw/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/bw/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/bw/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/memory_layer/kernel:0, (1024, 512), 
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (1536, 2048), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/luong_attention/attention_g:0, (), /device:GPU:0
  dynamic_seq2seq/decoder/attention/attention_layer/kernel:0, (1536, 512), /device:GPU:0
  dynamic_seq2seq/decoder/output_projection/kernel:0, (512, 30003), 
# Use the same embedding for source and target
# creating infer graph ...
  num_bi_layers = 1, num_bi_residual_layers=0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 0  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
  cell 1  LSTM, forget_bias=1  DeviceWrapper, device=/gpu:0
# Trainable variables
  embeddings/embedding_share:0, (30003, 512), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/fw/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/fw/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/bw/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/encoder/bidirectional_rnn/bw/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/memory_layer/kernel:0, (1024, 512), 
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0, (1536, 2048), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0, (1024, 2048), /device:GPU:0
  dynamic_seq2seq/decoder/attention/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0, (2048,), /device:GPU:0
  dynamic_seq2seq/decoder/attention/luong_attention/attention_g:0, (), /device:GPU:0
  dynamic_seq2seq/decoder/attention/attention_layer/kernel:0, (1536, 512), /device:GPU:0
  dynamic_seq2seq/decoder/output_projection/kernel:0, (512, 30003), 
# log_file=model/log_1548466695
2019-01-26 01:38:16.340262: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-26 01:38:16.451356: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-01-26 01:38:16.451755: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2019-01-26 01:38:16.451808: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-01-26 01:38:16.820537: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-26 01:38:16.820592: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-01-26 01:38:16.820625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-01-26 01:38:16.820971: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10758 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
2019-01-26 01:38:16.821839: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-01-26 01:38:16.821889: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-26 01:38:16.821927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-01-26 01:38:16.821958: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-01-26 01:38:16.822215: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10758 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
2019-01-26 01:38:16.822661: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-01-26 01:38:16.822700: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-26 01:38:16.822731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-01-26 01:38:16.822746: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-01-26 01:38:16.822996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10758 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
  loaded train model parameters from model/translate.ckpt-16000, time 8.31s
  loaded infer model parameters from model/translate.ckpt-16000, time 1.04s
  # 41
    src: The last bit with Bishop is indeed bad, it's bad writing and Darby even admitted that it wasn't the best thing ever (They had a whole subplot planned for Juno but it was scrapped) nnnewlinechar nnnewlinechar But you ARE told why you need to find the Sage's body before Abstergo.
    ref: Yes, but It's just disappointing that after all that work, instead of a big Hollywood ending, you just get told 'Oh, don't worry the bones are probably damaged and useless anyways' nnnewlinechar nnnewlinechar I really think since Desmond, Real life aspect of AC has suffered. To the point where what's the point of even having it? Unless of course there's something planned.
    nmt: I don't think it's bad writing, but I don't think that's what I'm saying. I'm not saying it's bad writing, but I don't think it's worth it. nnnewlinechar nnnewlinechar
  loaded eval model parameters from model/translate.ckpt-16000, time 0.51s
  eval dev: perplexity 98.88, time 2s, Sat Jan 26 01:38:33 2019.
  eval test: perplexity 98.88, time 2s, Sat Jan 26 01:38:36 2019.
2019-01-26 01:38:36.801422: I tensorflow/core/kernels/lookup_util.cc:376] Table trying to initialize from file data/vocab.bpe.from is already initialized.
2019-01-26 01:38:36.801431: I tensorflow/core/kernels/lookup_util.cc:376] Table trying to initialize from file data/vocab.bpe.from is already initialized.
  loaded infer model parameters from model/translate.ckpt-16000, time 0.49s
# External evaluation, global step 16000
  decoding to output model/output_dev_16000.
  done, num sentences 100, num translations per input 1, time 28s, Sat Jan 26 01:39:05 2019.
  bleu dev: 0.4
  saving hparams to model/hparams
# External evaluation, global step 16000
  decoding to output model/output_test_16000.
  done, num sentences 100, num translations per input 1, time 28s, Sat Jan 26 01:39:36 2019.
  bleu test: 0.4
  saving hparams to model/hparams
# Start step 16000, lr 0.001, Sat Jan 26 01:39:38 2019
# Init train iterator, skipping 0 elements
2019-01-26 01:40:00.393176: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:98] Filling up shuffle buffer (this may take a while): 1 of 128000
2019-01-26 01:40:00.393572: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:98] Filling up shuffle buffer (this may take a while): 2 of 128000
2019-01-26 01:40:21.267221: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:98] Filling up shuffle buffer (this may take a while): 928 of 128000
2019-01-26 01:40:21.267663: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:98] Filling up shuffle buffer (this may take a while): 929 of 128000
2019-01-26 01:40:30.866792: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:98] Filling up shuffle buffer (this may take a while): 935 of 128000
2019-01-26 01:40:57.284153: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:98] Filling up shuffle buffer (this may take a while): 1833 of 128000
2019-01-26 01:40:57.284309: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:98] Filling up shuffle buffer (this may take a while): 1834 of 128000
2019-01-26 01:41:00.175895: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:98] Filling up shuffle buffer (this may take a while): 28852 of 128000
2019-01-26 01:41:09.825936: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:136] Shuffle buffer filled.
  step 16100 lr 0.001 step-time 2.26s wps 3.19K ppl 65.70 gN 9.04 bleu 0.37, Sat Jan 26 01:43:24 2019
  step 16200 lr 0.001 step-time 4.02s wps 1.80K ppl 65.93 gN 13.10 bleu 0.37, Sat Jan 26 01:50:06 2019
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: data/train.bpe.to; Input/output error
	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?], [?,?], [?,?], [?], [?]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
	 [[{{node dynamic_seq2seq/decoder/LuongAttention/memory_layer/Tensordot/GatherV2_1/_291}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_2171_...GatherV2_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 88, in nmt_train
    tf.app.run(main=nmt.main, argv=[os.getcwd() + '\nmt\nmt\nmt.py'] + unparsed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/content/drive/testingv2/nmt-chatbot/nmt/nmt/nmt.py", line 599, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/content/drive/testingv2/nmt-chatbot/nmt/nmt/nmt.py", line 592, in run_main
    train_fn(hparams, target_session=target_session, summary_callback=summary_callback)
  File "/content/drive/testingv2/nmt-chatbot/nmt/nmt/train.py", line 358, in train
    step_result = loaded_train_model.train(train_sess)
  File "/content/drive/testingv2/nmt-chatbot/nmt/nmt/model.py", line 266, in train
    self.learning_rate])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: data/train.bpe.to; Input/output error
	 [[node IteratorGetNext (defined at /content/drive/testingv2/nmt-chatbot/nmt/nmt/utils/iterator_utils.py:196)  = IteratorGetNext[output_shapes=[[?,?], [?,?], [?,?], [?], [?]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
	 [[{{node dynamic_seq2seq/decoder/LuongAttention/memory_layer/Tensordot/GatherV2_1/_291}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_2171_...GatherV2_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'IteratorGetNext', defined at:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 88, in nmt_train
    tf.app.run(main=nmt.main, argv=[os.getcwd() + '\nmt\nmt\nmt.py'] + unparsed)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/content/drive/testingv2/nmt-chatbot/nmt/nmt/nmt.py", line 599, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/content/drive/testingv2/nmt-chatbot/nmt/nmt/nmt.py", line 592, in run_main
    train_fn(hparams, target_session=target_session, summary_callback=summary_callback)
  File "/content/drive/testingv2/nmt-chatbot/nmt/nmt/train.py", line 302, in train
    train_model = model_helper.create_train_model(model_creator, hparams, scope)
  File "/content/drive/testingv2/nmt-chatbot/nmt/nmt/model_helper.py", line 100, in create_train_model
    shard_index=jobid)
  File "/content/drive/testingv2/nmt-chatbot/nmt/nmt/utils/iterator_utils.py", line 196, in get_iterator
    tgt_seq_len) = (batched_iter.get_next())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 421, in get_next
    name=name)), self._output_types,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): data/train.bpe.to; Input/output error
	 [[node IteratorGetNext (defined at /content/drive/testingv2/nmt-chatbot/nmt/nmt/utils/iterator_utils.py:196)  = IteratorGetNext[output_shapes=[[?,?], [?,?], [?,?], [?], [?]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
	 [[{{node dynamic_seq2seq/decoder/LuongAttention/memory_layer/Tensordot/GatherV2_1/_291}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_2171_...GatherV2_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Btw, I resumed the code after stopping at 16k steps to quickly test the bot using inference.py.
All of the settings are default, except for the epochs (I've custom defined 5 epochs).

**Comment by Prickman** [comment]
I restarted train.py after deleting epochs_passed, and it gave me the same error again after only 100 steps this time.

**Comment by Prickman** [comment]
I re-ran prepare_data.py, and reliably trained up to 31k steps before training.py threw the same exception again. When I re-run training.py, it throws the same exception again. Any help please?

**Comment by kaiyu-tang** [comment]
@Prickman have you fixed the problem now?
