### ISSUE TITLE
Error with train.py "No module named tensorflow.python"

### ISSUE THREAD

**Issue by riannadsilva** [daniel-kukiela/nmt-chatbot#117]
So everything seems to work alright, until I reach the last stage train.py
Can someone point out what I'm doing wrong? Help   @daniel-kukiela , @Sentdex !!! :(

_Traceback (most recent call last): 
  File "train.py", line 7, in <module>
    from nmt import nmt
  File "C:\Users\User\nmt-chatbot/nmt\nmt\nmt.py", line 26, in <module>
    import tensorflow as tf
  _File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
ModuleNotFoundError: No module named 'tensorflow.python'_

<img width="792" alt="4" src="https://user-images.githubusercontent.com/44653968/52085747-8a33e880-25a5-11e9-9e54-f860fd200947.PNG">

**Comment by riannadsilva** [comment]
Resolved by downloading and installing Python version 3.6.5 (executable file).
