### ISSUE TITLE
when I run train.py i get the following error Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by aliNader** [daniel-kukiela/nmt-chatbot#122]

**Comment by aliNader** [comment]
this is the error details:

Traceback (most recent call last):                                                                                                                                                                 File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in                                                           from tensorflow.python.pywrap_tensorflow_internal import *                                                                                                                                     File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in                                                  _pywrap_tensorflow_internal = swig_import_helper()                                                                                                                                             File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper                                       _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)                                                                                                               File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module                                                                                                    return load_dynamic(name, filename, file)                                                                                                                                                      File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic                                                                                                   return _load(spec)                                                                                                                                                                           ImportError: DLL load failed: The specified module could not be found.                                                                                                                                                                                                                                                                                                                            During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                                                                               Traceback (most recent call last):                                                                                                                                                                 File "train.py", line 8, in                                                                                                                                                                from nmt import nmt                                                                                                                                                                            File "C:\Users\Ali\Documents\Visual Studio 2017\Projects\SequenceToSequenceModel\nmt-chatbot/nmt\nmt\nmt.py", line 26, in                                                                  import tensorflow as tf                                                                                                                                                                        File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 24, in                                                                           from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import                                                                                                               File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in                                                                    from tensorflow.python import pywrap_tensorflow                                                                                                                                                File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in                                                           raise ImportError(msg)                                                                                                                                                                       ImportError: Traceback (most recent call last):                                                                                                                                                    File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in                                                           from tensorflow.python.pywrap_tensorflow_internal import *                                                                                                                                     File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in                                                  _pywrap_tensorflow_internal = swig_import_helper()                                                                                                                                             File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper                                       _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)                                                                                                               File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module                                                                                                    return load_dynamic(name, filename, file)                                                                                                                                                      File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic                                                                                                   return _load(spec)                                                                                                                                                                           ImportError: DLL load failed: The specified module could not be found.
Failed to load the native TensorFlow runtime.                                                                                                                                                                                                                                                                                                                                                     See https://www.tensorflow.org/install/errors

**Comment by aliNader** [comment]
This is the full trace error:
Traceback (most recent call last):                                                                                                                                                                 File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in  from tensorflow.python.pywrap_tensorflow_internal import *                                                                                                                                     File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in                                                  _pywrap_tensorflow_internal = swig_import_helper()                                                                                                                                             File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper                                       _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)                                                                                                               File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module                                                                                                    return load_dynamic(name, filename, file)                                                                                                                                                      File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic                                                                                                   return _load(spec)                                                                                                                                                                           ImportError: DLL load failed: The specified module could not be found.                                                                                                                                                                                                                                                                                                                            During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                                                                               Traceback (most recent call last):                                                                                                                                                                 File "train.py", line 8, in                                                                                                                                                                from nmt import nmt                                                                                                                                                                            File "C:\Users\Ali\Documents\Visual Studio 2017\Projects\SequenceToSequenceModel\nmt-chatbot/nmt\nmt\nmt.py", line 26, in  import tensorflow as tf                                                                                                                                                                        File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 24, in                                                                           from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import                                                                                                               File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\__init__.py", line 49, in  from tensorflow.python import pywrap_tensorflow                                                                                                                                                File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in  raise ImportError(msg)                                                                                                                                                                       ImportError: Traceback (most recent call last):                                                                                                                                                    File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in from tensorflow.python.pywrap_tensorflow_internal import *                                                                                                                                     File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in                                                  _pywrap_tensorflow_internal = swig_import_helper()                                                                                                                                             File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper                                       _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)                                                                                                               File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module                                                                                                    return load_dynamic(name, filename, file)                                                                                                                                                      File "C:\Users\Ali\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic                                                                                                   return _load(spec)                                                                                                                                                                           ImportError: DLL load failed: The specified module could not be found.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Failed to load the native TensorFlow runtime.

**Comment by AfaqAnwar** [comment]
Have you installed Tensorflow using PIP?

I found that installing Tensorflow on Windows 10 using PIP results in DLL errors, especially when being configured with GPU acceleration. This gave me headaches for days on end, I was told to build Tensorflow from source and whole slew of other suggestions, until I found out Anaconda is a much better way of handling this.

I'm currently running Ubuntu 18.04, however this guide should point you in the right direction even if you're running Windows 10. 

[Installing Tensorflow with GPU Support - Puget Systems](https://www.pugetsystems.com/labs/hpc/Install-TensorFlow-with-GPU-Support-the-Easy-Way-on-Ubuntu-18-04-without-installing-CUDA-1170/l)

Be sure to specify the Python version while creating a virtual environment.

`conda create --name tf-gpu python=3.6`

**NOTE - If you do not want to run Tensorflow with GPU acceleration then use this command**

`conda install tensorflow`

instead of the original command posted in the article.

**Comment by Chadhendrixs** [comment]
it's because Paperspace's tensorflow-gpu version is too new. Do this to fix it: pip install --upgrade tensorflow-gpu==1.4﻿

**Comment by kaljitism** [comment]
Its the Cuda error, nothing can be done apart from modifying code base's tensorflow version migration to 2.x to match with current Cuda version.
