### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/test.from'

### ISSUE THREAD

**Issue by SharpBit** [daniel-kukiela/nmt-chatbot#134]
I put the .from and .to files in the new_data folder and i come upon this error:
```
File: test.bpe.from
Traceback (most recent call last):
  File "prepare_data.py", line 553, in <module>
    prepare()
  File "prepare_data.py", line 423, in prepare
    number_of_records = sum(1 for _ in open('{}{}'.format(preprocessing['train_folder'], file_name.replace('.bpe.', '.')), 'r', encoding='utf-8', buffering=131072))
FileNotFoundError: [Errno 2] No such file or directory: 'data/test.from'
```
The data folder was created after i ran `prepare_data.py` so don't know why it's expecting a file I was never told to put there

**Comment by kaljitism** [comment]
Use the same filenames or modify prepare_data.py
