### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.nn' has no attribute 'rnn_cel

### ISSUE THREAD

**Issue by jalakamkiran** [daniel-kukiela/nmt-chatbot#167]
Getting a attribute error like this
`Traceback (most recent call last):
  File "C:\Users\Inspired Kinematics\Desktop\nmt-chatbot\train.py", line 7, in <module>
    from nmt import nmt
  File "C:\Users\Inspired Kinematics\Desktop\nmt-chatbot/nmt\nmt\nmt.py", line 28, in <module>
    from . import inference
  File "C:\Users\Inspired Kinematics\Desktop\nmt-chatbot/nmt\nmt\inference.py", line 25, in <module>
    from . import gnmt_model
  File "C:\Users\Inspired Kinematics\Desktop\nmt-chatbot/nmt\nmt\gnmt_model.py", line 210, in <module>
    class GNMTAttentionMultiCell(tf.nn.rnn_cell.MultiRNNCell):
AttributeError: module 'tensorflow._api.v2.nn' has no attribute 'rnn_cell'`

Guessing it is a error due to version. Any workaround please?

**Comment by ashraq1455** [comment]
This error seems to be related to tensorflow version. Make sure you install the tensorflow version as in requirements.txt.

**Comment by Nathan-Chell** [comment]
I do believe you have installed tensorflow 2.x. This chatbot was written to use Tensorflow 1.12 And above, but importantly below Tensorflow 2.x. To fix this simply pip install tesnorflow-gpu==1.15.4

**Comment by dusty-dusty** [comment]
https://github.com/daniel-kukiela/nmt-chatbot/issues/143
