### ISSUE TITLE
Can't run train.py

### ISSUE THREAD

**Issue by Whooptie** [daniel-kukiela/nmt-chatbot#170]
when i try to run train.py after the data is prepaird ik get this problem:

========= RESTART: M:\AI\nmt-chatbot-master\nmt-chatbot-master\train.py ========
Traceback (most recent call last):
  File "M:\AI\nmt-chatbot-master\nmt-chatbot-master\train.py", line 8, in <module>
    from nmt import nmt
  File "M:\AI\nmt-chatbot-master\nmt-chatbot-master\nmt\nmt.py", line 28, in <module>
    from . import inference
  File "M:\AI\nmt-chatbot-master\nmt-chatbot-master\nmt\inference.py", line 25, in <module>
    from . import gnmt_model
  File "M:\AI\nmt-chatbot-master\nmt-chatbot-master\nmt\gnmt_model.py", line 261, in <module>
    class GNMTAttentionMultiCell(tf.nn.rnn_cell.MultiRNNCell):
AttributeError: module 'tensorflow._api.v2.nn' has no attribute 'rnn_cell'
>>> 

pleas help i'm a verry new newby to python

**Comment by dusty-dusty** [comment]
https://github.com/daniel-kukiela/nmt-chatbot/issues/143

**Comment by Nathan-Chell** [comment]
You are using Tensorflow 2.x. for this code you need to use Tensorflow 1.x preferably 1.15. You'll have to uninstall tf 2 and explicitly install tf 1.15 with: pip install tensorflow-gpu==1.15

**Comment by Whooptie** [comment]
I did install tensorflow 1.14 yesterday and it all worked, but wen i started training again it filles the shuffle and then its terminated, any idea why?  Btw i am only using cpu its a ryzen 5 1600, its running in ubuntu in virtualbox

**Comment by Nathan-Chell** [comment]
What do you mean by terminated? Any errors ? 

My best guess is a OOM error

**Comment by Whooptie** [comment]
no errors at all
# start step 0, lr 0.001, mon dec 21 13:30:47 2020
# Init train iterator, skipping 0 elements
2020-12-21 13:30:58.275320: I tensorflow/cor/kernels/shuffle_dataset_op.cc:110] Filling up shuffle buffer (this may take a while): 101395 of 128000
2020-12-21 13:31:00.976069: I tensorflow/cor/kernels/shuffle_dataset_op.cc:121] shuffle buffer filled
terminated

then the whole system freezes and training stopped

**Comment by M4A1SD** [comment]
> You are using Tensorflow 2.x. for this code you need to use Tensorflow 1.x preferably 1.15. You'll have to uninstall tf 2 and explicitly install tf 1.15 with: pip install tensorflow-gpu==1.15

![image](https://user-images.githubusercontent.com/109923283/183404220-6c09b61c-d942-4705-b243-7f0e7c70af2b.png)

this pip doesnt work
i tried downloading manually [ https://pypi.org/project/tensorflow-gpu/1.15.0/#files ] 
![image](https://user-images.githubusercontent.com/109923283/183404755-144c5d2a-f5e1-48af-ae49-8aaf3b10ce89.png)

is there another way?

**Comment by Nathan-Chell** [comment]
> > You are using Tensorflow 2.x. for this code you need to use Tensorflow 1.x preferably 1.15. You'll have to uninstall tf 2 and explicitly install tf 1.15 with: pip install tensorflow-gpu==1.15
> 
> ![image](https://user-images.githubusercontent.com/109923283/183404220-6c09b61c-d942-4705-b243-7f0e7c70af2b.png)
> 
> this pip doesnt work i tried downloading manually [ https://pypi.org/project/tensorflow-gpu/1.15.0/#files ] ![image](https://user-images.githubusercontent.com/109923283/183404755-144c5d2a-f5e1-48af-ae49-8aaf3b10ce89.png)
> 
> is there another way?

You are using python 3.10 which no longer supports tensorflow 1.x. You need to uninstall it and download python 3.7 - or you can create a new virtual environment if you have gone that route.
