### ISSUE TITLE
ERROR: cannot import name 'nmt' from 'nmt'

### ISSUE THREAD

**Issue by CallMePeteio** [daniel-kukiela/nmt-chatbot#172]
hi i am getting thi error code when i try to run setup.py:

![image](https://user-images.githubusercontent.com/75163751/105627665-70e27180-5e38-11eb-92dd-f4c34dcd59ef.png)

i have looked on both of the other threads regarding this issue with no sucsess, i have also asked an engeneer that i know.

**Comment by NoCodeAvaible** [comment]
There is no module nmt to import.
Check the following directory C:\Users\xyz\Desktop\chatbot\nmt-chatbot-master\nmt\ if it is empty clone this repo using --recursive mod

$ git clone --recursive https://github.com/daniel-kukiela/nmt-chatbot
(or)

$ git clone --branch v0.1 --recursive https://github.com/daniel-kukiela/nmt-chatbot.git 
#for a version featured in Sentdex tutorial

**Comment by YashrajP9** [comment]
I have tried cloning both the given links seperately and tried to run the project as per the setup instructtions still i am facing errors
`Traceback (most recent call last):
  File "C:\Users\yashr\Downloads\SAYKA-Intelligent-Personal-Assistant-main\SAYKA-Intelligent-Personal-Assistant-main\nmt-chatbot\train.py", line 8, in <module>
    from nmt import nmt
  File "C:\Users\yashr\Downloads\SAYKA-Intelligent-Personal-Assistant-main\SAYKA-Intelligent-Personal-Assistant-main\nmt-chatbot/nmt\nmt\nmt.py", line 28, in <module>
    from . import inference
  File "C:\Users\yashr\Downloads\SAYKA-Intelligent-Personal-Assistant-main\SAYKA-Intelligent-Personal-Assistant-main\nmt-chatbot/nmt\nmt\inference.py", line 25, in <module>
    from . import gnmt_model
  File "C:\Users\yashr\Downloads\SAYKA-Intelligent-Personal-Assistant-main\SAYKA-Intelligent-Personal-Assistant-main\nmt-chatbot/nmt\nmt\gnmt_model.py", line 261, in <module>
    class GNMTAttentionMultiCell(tf.nn.rnn_cell.MultiRNNCell):
AttributeError: module 'tensorflow._api.v2.nn' has no attribute 'rnn_cell'`
Also my nmt folder has another nmt folder which contains all the files,
i tried copy pasting those files from nmt-chatbot>nmt>nmt(all file) to nmt-chatbot>nmt and tried running it again still i am getting the same error.
Please help me out with the issue.
