### ISSUE TITLE
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[512,100003]

### ISSUE THREAD

**Issue by noahchalifour** [daniel-kukiela/nmt-chatbot#23]
I created my own training data using the scripts in sentdex's tutorials and now I'm trying to run the train.py script and I keep getting this error:

`Traceback (most recent call last):
  File "train.py", line 18, in <module>
    tf.app.run(main=nmt.main, argv=[os.getcwd() + '\nmt\nmt\nmt.py'] + unparsed)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/nmt.py", line 539, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/nmt.py", line 532, in run_main
    train_fn(hparams, target_session=target_session)
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/train.py", line 294, in train
    step_result = loaded_train_model.train(train_sess)
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/model.py", line 245, in train
    self.learning_rate])
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[512,100003]
	 [[Node: gradients/dynamic_seq2seq/decoder/output_projection/Tensordot/MatMul_grad/MatMul_1 = MatMul[T=DT_FLOAT, _class=["loc:@dynamic_seq2seq/decoder/output_projection/Tensordot/MatMul"], transpose_a=true, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](dynamic_seq2seq/decoder/output_projection/Tensordot/Reshape, gradients/dynamic_seq2seq/decoder/output_projection/Tensordot_grad/Reshape)]]
	 [[Node: gradients/dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/TrainingHelperNextInputs/cond/Merge_grad/cond_grad/_215 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1567_gradients/dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/TrainingHelperNextInputs/cond/Merge_grad/cond_grad", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopgradients/dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/TrainingHelperNextInputs/cond/TensorArrayReadV3_grad/TensorArrayWrite/TensorArrayWriteV3/Switch/_49)]]

Caused by op 'gradients/dynamic_seq2seq/decoder/output_projection/Tensordot/MatMul_grad/MatMul_1', defined at:
  File "train.py", line 18, in <module>
    tf.app.run(main=nmt.main, argv=[os.getcwd() + '\nmt\nmt\nmt.py'] + unparsed)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/nmt.py", line 539, in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/nmt.py", line 532, in run_main
    train_fn(hparams, target_session=target_session)
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/train.py", line 222, in train
    train_model = model_helper.create_train_model(model_creator, hparams, scope)
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/model_helper.py", line 108, in create_train_model
    extra_args=extra_args)
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/attention_model.py", line 61, in __init__
    extra_args=extra_args)
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/model.py", line 139, in __init__
    colocate_gradients_with_ops=hparams.colocate_gradients_with_ops)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 353, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py", line 922, in _MatMulGrad
    grad_b = math_ops.matmul(a, grad, transpose_a=True)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1891, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2437, in _mat_mul
    name=name)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'dynamic_seq2seq/decoder/output_projection/Tensordot/MatMul', defined at:
  File "train.py", line 18, in <module>
    tf.app.run(main=nmt.main, argv=[os.getcwd() + '\nmt\nmt\nmt.py'] + unparsed)
[elided 5 identical lines from previous traceback]
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/attention_model.py", line 61, in __init__
    extra_args=extra_args)
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/model.py", line 97, in __init__
    res = self.build_graph(hparams, scope=scope)
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/model.py", line 284, in build_graph
    encoder_outputs, encoder_state, hparams)
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/model.py", line 407, in _build_decoder
    logits = self.output_layer(outputs.rnn_output)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/core.py", line 156, in call
    [0]])
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2520, in tensordot
    ab_matmul = matmul(a_reshape, b_reshape)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1891, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2437, in _mat_mul
    name=name)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[512,100003]
	 [[Node: gradients/dynamic_seq2seq/decoder/output_projection/Tensordot/MatMul_grad/MatMul_1 = MatMul[T=DT_FLOAT, _class=["loc:@dynamic_seq2seq/decoder/output_projection/Tensordot/MatMul"], transpose_a=true, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](dynamic_seq2seq/decoder/output_projection/Tensordot/Reshape, gradients/dynamic_seq2seq/decoder/output_projection/Tensordot_grad/Reshape)]]
	 [[Node: gradients/dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/TrainingHelperNextInputs/cond/Merge_grad/cond_grad/_215 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1567_gradients/dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/TrainingHelperNextInputs/cond/Merge_grad/cond_grad", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopgradients/dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/TrainingHelperNextInputs/cond/TensorArrayReadV3_grad/TensorArrayWrite/TensorArrayWriteV3/Switch/_49)]]`

I am using the exact same PaperSpace setup with the ML in a Box...

**Comment by daniel-kukiela** [comment]
You are trying to use pretty big vocab. Try to use lower one.

**Comment by Hyperclaw79** [comment]
@daniel-kukiela I am getting the same error as above even after reducing my `vocab_size` down to 5000 and the trained data samples generated by `prepare_data.py` to 10% of their actual size.

## Error
```py
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[6272,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[Node: gradients/dynamic_seq2seq/decoder/output_projection/Tensordot/MatMul_grad/MatMul = MatMul[T=DT_FLOAT, _class=["loc:@dynamic_seq2seq/decoder/output_projection/Tensordot/MatMul"], transpose_a=false, transpose_b=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/dynamic_seq2seq/decoder/output_projection/Tensordot_grad/Reshape, dynamic_seq2seq/decoder/output_projection/Tensordot/Reshape_1)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Node: gradients/dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/decoder/attention/luong_attention/mul_grad/Reshape/_658 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_3428_gradients/dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/decoder/attention/luong_attention/mul_grad/Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopgradients/dynamic_seq2seq/decoder/decoder/while/BasicDecoderStep/decoder/attention/attention_layer/MatMul/Enter_grad/Switch/_71)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```

## Config:
OS: Windows 10
Python: 3.6.4
Tensorflow: tensorflow_gpu-1.5.0rc1-cp36-cp36m-win_amd64.whl
CUDA: 9.0
CuDNN: 7.05
RAM: 8GB
VM: 2GB
GPU: 2GB Nvidia 920M
Settings.py: https://hastebin.com/qakorebudu.py

I know I'm using a nightly build of tensorflow but this doesn't seem to be a compatibility error. Neither does it seem like as a memory overload as it says given its small shape values and when I ran nvidia-smi.exe, TF was the only process consuming about half the GPU memory.
If this is a bug in the unofficial build, I'll have to try it out again using cuda 8 and tf14 (which I prefer less).
TYIA

~HT

**Comment by daniel-kukiela** [comment]
I'm not sure why you are getting that error. It's possible that it's still too big for 2GB card.
What you can try to do:
- lower batch size
- lower num_units

I'll try to use GPU with only 2GB of VRAM, but i need couple of days to do that. I didn't try nightly builds as well.

Did you run that on included sample data or some own corpus?

**Comment by MLguy07** [comment]
Even I'm gettings the same error. Has anyone figured out a solution?

**Comment by ogabrielluiz** [comment]
I'm getting the same error on a GTX 1070 8GB of VRAM.

**Comment by daniel-kukiela** [comment]
What training dataset are you using and what are settings (did you change them)?

**Comment by ogabrielluiz** [comment]
I downloaded the one from Kaggle and edited the code to get the data from
it instead of the json file. The From and To files seem to be as they
should.

Em seg, 4 de jun de 2018 09:19, Daniel Kukieła <notifications@github.com>
escreveu:

**Comment by pranshu19chester** [comment]
I used my training data but didn't change the initial 100 lines 'tst' files, it was working till but my bleu score was stuck at 0. I increased my 'tst' files to around 10,000 lines and I'm getting ResourceExhaustedError.

**Comment by mgrigajtis** [comment]
I have the same problem.  I have an NVIDIA Geforce GTX 950 with almost 2 gigs of memory free when I start training my model.  I get the ResourceExhaustedError every time, no matter what I set the other variables to.

**Comment by YaduKini** [comment]
I'm getting the same ResourceExhaustedError. I'm using the GPU on floydhub which has 61GB of RAM.

**Comment by YaduKini** [comment]
Did anyone get a solution for it?

**Comment by ajoseph12** [comment]
I too get a 'ResourceExhaustedError' when running version 0.3 of the code (the lastest). However, the error no longer persists when I use version 0.1 of the code (the one used in Sentdex's tutorial).

**Comment by daniel-kukiela** [comment]
So there are multiple factors that might cause OOM.

@ogabrielluiz not sure about Kaggle dataset, but it might just contain sentences longer that 1000 chars (that's the limit for our messages iirc). Longer sentences require more vram.

@pranshu19chester please look here: https://github.com/daniel-kukiela/nmt-chatbot/issues/66#issuecomment-401332886

@Adityagrao to use more than one gpu you have to add `num_gpus` in `hparams` section in `settings.py` and set it to desired number of GPUs. Keep in mid it won;t help much with speed - reference: https://github.com/tensorflow/nmt#wmt-german-english

@mgrigajtis default settings are tuned to 4 GB of VRAM with sample dataset. If you are using card with less amount of vram or even different dataset, you have to tune params.

@YaduKini Can you tell more? 61GB is more than required. Are you sure it's one GPU with direct/own RAM?

@ajoseph12 0.1 was tuned for 4 GB of VRAM, newwer releases changed something and it requires a bit more than 4 GB of VRAM with the same settings. You have to tune settings with your dataset and GPU anyway.

**Comment by athuldevin** [comment]
i have the same problem nvidia gtx 930m (2gb)
but i fixed
only changed num_units in settings to 256 and it trains with default dataset provided

**Comment by darvida** [comment]
where can i find the settings to change the num_units value ?

**Comment by daniel-kukiela** [comment]
In `setup/settings.py`, `hparams` section.

**Comment by Paulik8** [comment]
This error means you haven't enough memory that you really need. If you have big images try resize your images to medium size. For example, if you have 1024x682 image, halve ones and get 512x341.

**Comment by ahmadasghar1992** [comment]
> In `setup/settings.py`, `hparams` section.

Hi,
Can you please tell me where can I find settings.py? Is it in the site packages of tensorflow?

**Comment by sakshijain032** [comment]
> In `setup/settings.py`, `hparams` section.

Can you elaborate where can I get it

**Comment by stefaneadna** [comment]
diminui o tamanho do meu batch e funcionoi
