### ISSUE TITLE
Can't import inference

### ISSUE THREAD

**Issue by flamablecharlie** [daniel-kukiela/nmt-chatbot#28]
So using the example, I should be able to use

`from nmt-chatbot.inference import inference`

But when I try, I get this:

```
>>> from nmt-chatbot.inference import inference
  File "<stdin>", line 1
    from nmt-chatbot.inference import inference
            ^
SyntaxError: invalid syntax
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
  File "<stdin>", line 1
    from nmt-chatbot.inference import inference
            ^
SyntaxError: invalid syntax
>>> 
```
So is there a way to correctly import it?

**Comment by umangkr** [comment]
just rename the "nmt-chatbot" filename to anything else like "chatbot"
and then use "from chatbot.inference import inference"

**Comment by flamablecharlie** [comment]
That didn't work. :(

**Comment by Hyperclaw79** [comment]
Make sure you are not doing this from within the nmt-chatbot folder.

**Comment by flamablecharlie** [comment]
Completely separate folder. Same result.

**Comment by daniel-kukiela** [comment]
That's an unfortunate mistake to use dash in module name.
But with dash replaced with underscore:
`from nmt_chatbot.inference import inference`
that works for me.

Please doublecheck that.
