### ISSUE TITLE
requirements.txt fails to install

### ISSUE THREAD

**Issue by spiderwisp** [daniel-kukiela/nmt-chatbot#39]
Am I missing GPU support or something? 

Collecting tensorflow-gpu>=1.4.0 (from -r requirements.txt (line 1))
  Downloading tensorflow_gpu-1.5.0-cp35-cp35m-manylinux1_x86_64.whl (201.9MB)
    99% |████████████████████████████████| 201.9MB 21.8MB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/_vendor/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/home/science/tf-demo/tensorflow-dev/lib/python3.5/site-packages/pip/_vendor/cachecontrol/serialize.py", line 86, in dumps
    data, separators=(",", ":"), sort_keys=True,
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
MemoryError

**Comment by daniel-kukiela** [comment]
Looks like you have insufficient RAM maybe?
Try to add `--no-cache-dir`

**Comment by spiderwisp** [comment]
Adding RAM did fix this problem. Thank you!
