### ISSUE TITLE
How to import nmt-chatbot as package?

### ISSUE THREAD

**Issue by spiderwisp** [daniel-kukiela/nmt-chatbot#42]
Everything works great for me in your README, until I try to import inference.

The README says to use:

`from nmt-chatbot.inference import inference`

But I get a syntax error trying to use `nmt-chatbot` because of the hyphen. If I rename the `nmt-chatbot` folder to `nmt_chatbot` and change the PATHS in the `hparams` file I can import like `from nt_chatbot.inference import inference` but something else checks for the `nmt-chatbot` directory and I get this error:

```
Traceback (most recent call last):
  File "/var/www/scripts/test.py", line 8, in 
    print(inference("Hello!"))
  File "/var/www/scripts/nmt_chatbot/inference.py", line 186, in inference
    answers_list = process_questions(questions, include_blacklisted)
  File "/var/www/scripts/nmt_chatbot/inference.py", line 238, in process_questions
    answers_list = inference_helper(prepared_questions)
  File "/var/www/scripts/nmt_chatbot/inference.py", line 163, in start_inference
    inference_object = do_start_inference(out_dir, hparams)
  File "/var/www/scripts/nmt_chatbot/inference.py", line 59, in do_start_inference
    flags.ckpt = tf.train.latest_checkpoint(flags.out_dir)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1812, in latest_checkpoint
    if file_io.get_matching_files(v2_path) or file_io.get_matching_files(
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 337, in get_matching_files
    for single_filename in filename
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /var/www/scripts/nmt-chatbot/model; No such file or directory
```

**Comment by spiderwisp** [comment]
Ok so this other issue here: https://github.com/daniel-kukiela/nmt-chatbot/issues/38 helped answer my question.

Once I changed the path in the `checkpoint` folder to correspond to the new `nmt_chatbot` directory it works.

**Comment by daniel-kukiela** [comment]
Yes, i will update docs. Sorry you had to search.

**Comment by spiderwisp** [comment]
Thanks. No apologies necessary. I very much appreciate your work and help.

**Comment by daniel-kukiela** [comment]
Info about importing has been updated.
