### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by spiderwisp** [daniel-kukiela/nmt-chatbot#46]
So I keep hitting this error when SSH'ing into my boxes, and so I decided to follow along exactly with Sentdex's tutorial and did exactly as he did on paperspace and when I go to `train.py` I get the following error.

Before I reinstalled TensorFlow and it corrected the problem (On a Digital Ocean 32CPU box). Doesn't seem to work on Paperspace and not sure why I'm getting this error when Harrison doesn't in the tutorial :/

This is the position in the tutorial in which I get the following: https://youtu.be/040CfFRJ9Rs?t=879

Perhaps related: https://github.com/tensorflow/tensorflow/issues/15604
```
paperspace@psh728wf0:~/Desktop/nmt-chatbot$ python train.py
Traceback (most recent call last):
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/paperspace/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/paperspace/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from nmt import nmt
  File "/home/paperspace/Desktop/nmt-chatbot/nmt/nmt/nmt.py", line 26, in <module>
    import tensorflow as tf
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/paperspace/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/paperspace/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/paperspace/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
paperspace@psh728wf0:~/Desktop/nmt-chatbot$ 

```

**Comment by spiderwisp** [comment]
Ok, so this is actually a bug with TensorFlow it seems.

The problems seems to be that tensorflow-gpu is version 1.6 when we need 1.4. So the following command fixed it for me (of course after hours of scratching my head I figure it out right after posting :))

`pip install --upgrade tensorflow-gpu==1.4`

I found the solution here: https://github.com/tensorflow/tensorflow/issues/15604

**Comment by daniel-kukiela** [comment]
Interesting, i have to checkt that.
I am using TF 1.5 (on Windows machine) successfully with that code.

**Comment by devanshi21** [comment]
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from nmt import nmt
ImportError: cannot import name 'nmt'

I am getting this error ,I have tensorflow 1.4 version with python 3.6.

**Comment by daniel-kukiela** [comment]
Try `pip install tensorflow --upgrade --force-reinstall`
use `tensorflow-gpu` for gpu version of course.

**Comment by TestPW** [comment]
`$ python train.py `
Output 
Training model...
Epoch: 1, learning rate: 0.001 - already passed
Epoch: 2, learning rate: 0.0001 - already passed
Epoch: 3, learning rate: 1e-05 - already passed

Training finished
 `$ python .\inference.py `


Starting

 interactive mode (first response will take a while):

 hey
Traceback (most recent call last):
  File ".\inference.py", line 308, in <module>
    answers = inference_internal(question)[0]
  File ".\inference.py", line 212, in inference_internal
    return process_questions(questions, True)
  File ".\inference.py", line 260, in process_questions
    answers_list = inference_helper(prepared_questions)
  File ".\inference.py", line 181, in start_inference
    return inference_helper(question)
  File ".\inference.py", line 174, in <lambda>
    inference_helper = lambda question: do_inference(question, *inference_object)
  File ".\inference.py", line 98, in do_inference
    loaded_infer_model = nmt.inference.model_helper.load_model(infer_model.model, flags.ckpt, sess, "infer")
  File "C:\Python\ChatBot\nmt-chatbot/nmt\nmt\model_helper.py", line 483, in load_model
    model.saver.restore(session, ckpt)
  File "C:\Users\Test\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1662, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it isNone.

I am getting above error on windows 10.@daniel-kukiela Could you please help me on this ?
Note : No Checkpoint files created in Model directory.
