### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data//corpus_size'

### ISSUE THREAD

**Issue by nicolagheza** [daniel-kukiela/nmt-chatbot#57]
`2018-04-10 11:11:54 PSTTraining model...
2018-04-10 11:11:54 PST
2018-04-10 11:11:54 PSTTraceback (most recent call last):
2018-04-10 11:11:54 PSTFile "train.py", line 90, in <module>
2018-04-10 11:11:54 PSTtrain()
2018-04-10 11:11:54 PSTFile "train.py", line 25, in train
2018-04-10 11:11:54 PSTwith open('{}/corpus_size'.format(preprocessing['train_folder']), 'r') as f:
2018-04-10 11:11:54 PSTFileNotFoundError: [Errno 2] No such file or directory: 'data//corpus_size'
2018-04-10 11:11:58 PST`

Hello, I was trying to train the model on floydhub and I got this error. Do you know what I am doing wrong?

**Comment by daniel-kukiela** [comment]
Did you start fresh with that model, or you are using some data prepared previously.
That looks either like some bug i don'y know of, or like you used previously prepared data with new code.
Can you look at `data` folder if there is `corpus_size` file?

**Comment by nicolagheza** [comment]
I cloned the repo and run train.py as a job on Floydhub. The thing is that I do not have a folder called data / I don't have a corpus_size file in new_data

**Comment by daniel-kukiela** [comment]
Did you even do preparation steps (included in readme)?

**Comment by nicolagheza** [comment]
Ops. I am sorry, that's actually what I have missed. 
Thanks for clarifying things up.
