### ISSUE TITLE
ValueError: empty range for randrange() (%d %d %d) % (istart, istop, width)

### ISSUE THREAD

**Issue by alexjperkins** [daniel-kukiela/nmt-chatbot#70]
So when I run the train.py model, everything starts off okay, creating a train model and infer model with fresh params.

But then I can't go any further and I get the following error:

Traceback (most recent call last):
  File "train.py", line 18, in <module>
    tf.app.run(main=nmt.main, argv=[os.getcwd() + '\nmt\nmt\nmt.py'] + unparsed)
  File "C:\Users\alexjperkins\AppData\Local\Programs\Python\Python36\lib\site-pa                                                                                                                                                                                               ckages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:\Dev\Python\Tensorflow\Chatbot\nmt-chatbot/nmt\nmt\nmt.py", line 539,                                                                                                                                                                                                in main
    run_main(FLAGS, default_hparams, train_fn, inference_fn)
  File "C:\Dev\Python\Tensorflow\Chatbot\nmt-chatbot/nmt\nmt\nmt.py", line 532,                                                                                                                                                                                                in run_main
    train_fn(hparams, target_session=target_session)
  File "C:\Dev\Python\Tensorflow\Chatbot\nmt-chatbot/nmt\nmt\train.py", line 266                                                                                                                                                                                               , in train
    sample_tgt_data)
  File "C:\Dev\Python\Tensorflow\Chatbot\nmt-chatbot/nmt\nmt\train.py", line 138                                                                                                                                                                                               , in run_full_eval
    sample_src_data, sample_tgt_data)
  File "C:\Dev\Python\Tensorflow\Chatbot\nmt-chatbot/nmt\nmt\train.py", line 51,                                                                                                                                                                                                in run_sample_decode
    infer_model.batch_size_placeholder, summary_writer)
  File "C:\Dev\Python\Tensorflow\Chatbot\nmt-chatbot/nmt\nmt\train.py", line 429                                                                                                                                                                                               , in _sample_decode
    decode_id = random.randint(0, len(src_data) - 1)
  File "C:\Users\alexjperkins\AppData\Local\Programs\Python\Python36\lib\random.                                                                                                                                                                                               py", line 220, in randint
    return self.randrange(a, b+1)
  File "C:\Users\alexjperkins\AppData\Local\Programs\Python\Python36\lib\random.                                                                                                                                                                                               py", line 198, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop,                                                                                                                                                                                                width))
ValueError: empty range for randrange() (0,0, 0)

I'm on windows 10, with the latest tensorflow gpu install (this works fine) and in Python3.6.

The hparams are as follows:
\hparams
  attention=scaled_luong
  attention_architecture=standard
  batch_size=128
  beam_width=10
  best_bleu=0
  best_bleu_dir=C:\Dev\Python\Tensorflow\Chatbot\nmt-chatbot\model\best_bleu
  check_special_token=True
  colocate_gradients_with_ops=True
  decay_factor=1.0
  decay_steps=10000
  dev_prefix=C:\Dev\Python\Tensorflow\Chatbot\nmt-chatbot\data\tst2012
  dropout=0.2
  encoder_type=bi
  eos=</s>
  epoch_step=0
  forget_bias=1.0
  infer_batch_size=32
  init_op=uniform
  init_weight=0.1
  learning_rate=0.001
  learning_rate_decay_scheme=
  length_penalty_weight=1.0
  log_device_placement=False
  max_gradient_norm=5.0
  max_train=0
  metrics=['bleu']
  num_buckets=5
  num_embeddings_partitions=0
  num_gpus=1
  num_layers=2
  num_residual_layers=0
  num_train_steps=500000
  num_translations_per_input=10
  num_units=512
  optimizer=adam
  out_dir=C:\Dev\Python\Tensorflow\Chatbot\nmt-chatbot\model
  output_attention=True
  override_loaded_hparams=False
  pass_hidden_state=True
  random_seed=None
  residual=False
  share_vocab=False
  sos=<s>
  source_reverse=False
  src=from
  src_max_len=50
  src_max_len_infer=None
  src_vocab_file=C:\Dev\Python\Tensorflow\Chatbot\nmt-chatbot\data\vocab.from
  src_vocab_size=100003
  start_decay_step=0
  steps_per_external_eval=None
  steps_per_stats=100
  subword_option=
  test_prefix=C:\Dev\Python\Tensorflow\Chatbot\nmt-chatbot\data\tst2013
  tgt=to
  tgt_max_len=50
  tgt_max_len_infer=None
  tgt_vocab_file=C:\Dev\Python\Tensorflow\Chatbot\nmt-chatbot\data\vocab.to
  tgt_vocab_size=100003
  time_major=True
  train_prefix=C:\Dev\Python\Tensorflow\Chatbot\nmt-chatbot\data\train
  unit_type=lstm
  vocab_prefix=C:\Dev\Python\Tensorflow\Chatbot\nmt-chatbot\data\vocab
  warmup_scheme=t2t
  warmup_steps=0

Any help would be greatly appreciated!

**Comment by daniel-kukiela** [comment]
Are you using our fork of nmt (in nmt folder)? Did you clone repo recursively? number of lines doesn't match what i have.

**Comment by daniel-kukiela** [comment]
Another question - are you using most recent version of code?
