### ISSUE TITLE
NMT inference.py--cannot import name FOO

### ISSUE THREAD

**Issue by iocohen** [daniel-kukiela/nmt-chatbot#76]
Hi guys, Trying to use the inference.py from nmt folder. I receive a lot of errors, saying  
```
___File "/Users/Downloads/nmt-chatbot/nmt/nmt/model.py", line 27, in <module>
    from . import model_helper
ImportError: cannot import name 'model_helper'___
```

This is an example. 
```
Traceback (most recent call last):
  File "/Users/Downloads/nmt-chatbot/nmt/nmt/inference.py", line 24, in <module>
    from . import attention_model
ImportError: cannot import name 'attention_model'
```

How can i bypass this error?

**Comment by daniel-kukiela** [comment]
Why are you going to use inference.py in nmt folder? NMT is just a tool used in our code. You shouldn't run anything from nmt folder directly.
