### ISSUE TITLE
while running inference.py this error occured

### ISSUE THREAD

**Issue by indrajeetgajbhiye** [daniel-kukiela/nmt-chatbot#80]
C:\python\Tutorials\nmt-chatbot>python inference.py
Traceback (most recent call last):
  File "inference.py", line 16, in <module>
    from scorer import score_answers
  File "C:\python\Tutorials\nmt-chatbot/core\scorer.py", line 1, in <module>
    import Levenshtein
ModuleNotFoundError: No module named 'Levenshtein'

thanks and regards

**Comment by daniel-kukiela** [comment]
Did you pip install requirements?

**Comment by indrajeetgajbhiye** [comment]
Yes I did..

**Comment by daniel-kukiela** [comment]
do:
`pip install python-Levenshtein`
and let me know about results

**Comment by indrajeetgajbhiye** [comment]
Starting interactive mode (first response will take a while):

> hi
Traceback (most recent call last):
  File "C:\python\Tutorials\nmt-chatbot\inference.py", line 308, in <module>
    answers = inference_internal(question)[0]
  File "C:\python\Tutorials\nmt-chatbot\inference.py", line 212, in inference_internal
    return process_questions(questions, True)
  File "C:\python\Tutorials\nmt-chatbot\inference.py", line 260, in process_questions
    answers_list = inference_helper(prepared_questions)
  File "C:\python\Tutorials\nmt-chatbot\inference.py", line 181, in start_inference
    return inference_helper(question)
  File "C:\python\Tutorials\nmt-chatbot\inference.py", line 174, in <lambda>
    inference_helper = lambda question: do_inference(question, *inference_object)
  File "C:\python\Tutorials\nmt-chatbot\inference.py", line 98, in do_inference
    loaded_infer_model = nmt.inference.model_helper.load_model(infer_model.model, flags.ckpt, sess, "infer")
  File "C:\python\Tutorials\nmt-chatbot/nmt\nmt\model_helper.py", line 483, in load_model
    model.saver.restore(session, ckpt)
  File "C:\python\lib\site-packages\tensorflow\python\training\saver.py", line 1796, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.



now that problem is solved thanks for the help. 

but the new error is occured.  please let me know about it. its tensorflow error. can you help me about this.

**Comment by daniel-kukiela** [comment]
Did you train your model? Looks like there are no any checkpoint.
